name: Windows RDP Server

on:
  workflow_dispatch:

jobs:
  secure-rdp:
    runs-on: windows-2022
    timeout-minutes: 3600
    defaults:
      run:
        shell: pwsh
    
    steps:
      - name: Random Number Generator
        id: time-stamp-generator
        run: echo "time-stamp=$(echo $(date +%s%6N))" >> $GITHUB_OUTPUT
        shell: bash
        
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Cache Primes
        id: cache-primes
        uses: actions/cache@v4
        with:
          path: |
            D:/cache
          key: ${{ runner.os }}-primes-${{ steps.time-stamp-generator.outputs.time-stamp }}
          restore-keys: |
            ${{ runner.os }}-primes-
            ${{ runner.os }}-
          
      - name: Configure Core RDP Settings
        shell: pwsh
        run: .github/workflows/scripts/win-configure-rdp.ps1

      - name: change pss securit
        shell: pwsh
        env:
          WORK_SPACE: ${{ github.workspace }}
        run: .github/workflows/scripts/win-configure-security.ps1

      - name: Create RDP User with Secure Password
        env:
          LOGIN_PASSWORD: ${{ secrets.LOGIN_PASSWORD }}
        shell: pwsh
        run: .github/workflows/scripts/win-create-user.ps1

      - name: Install Tailscale
        env:
          WORK_SPACE: ${{ github.workspace }}
        shell: pwsh
        run: |
          # .github/workflows/scripts/win-install-tailscale.ps1
          # Install Tailscale MSI
          #Remove-Item -Path "C:\ProgramData\chocolatey\logs\chocolatey.log"
          #choco uninstall tailscale --force
          choco install tailscale
          #Get-ChildItem -Path "$env:ProgramFiles" 
          #Get-Content -Path "C:\ProgramData\chocolatey\logs\chocolatey.log"

      - name: Establish Tailscale Connection
        shell: pwsh
        env:
          TAILSCALE_AUTH_KEY: ${{ secrets.TAILSCALE_AUTH_KEY }}
          WORK_SPACE: ${{ github.workspace }}
        run: .github/workflows/scripts/win-establish-ts.ps1

      - name: Verify RDP Accessibility
        shell: pwsh
        run: .github/workflows/scripts/win-verify-rdp.ps1

      - name: Maintain Connection
        shell: pwsh
        run: |
          Write-Host "`n=== RDP ACCESS ==="
          Write-Host "Address: $env:TAILSCALE_IP"
          Write-Host "Username: vum"
          Write-Host "Password: $(echo $env:RDP_CREDS)"
          Write-Host "==================`n"      
          $global:file = Get-Content "${{ github.workspace }}\state.txt"
          while ($global:file -eq "true") {
            Write-Host "[$(Get-Date)] RDP Active"
            Start-Sleep -Seconds 10
            $global:file = Get-Content "${{ github.workspace }}\state.txt"
          }
