name: Windows RDP Server

on:
  workflow_dispatch:

jobs:
  secure-rdp:
    runs-on: windows-latest
    timeout-minutes: 3600

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Cache Primes
        id: cache-primes
        uses: actions/cache@v4
        with:
          path: |
            C:\Users\vum
            D:\cache
          key: ${{ runner.os }}-primes
          
      - name: Configure Core RDP Settings
        shell: pwsh
        run: .github/workflows/scripts/win-configure-rdp.ps1

      - name: Create RDP User with Secure Password
        env:
          LOGIN_PASSWORD: ${{ secrets.LOGIN_PASSWORD }}
        shell: pwsh
        run: .github/workflows/scripts/win-create-user.ps1

      - name: Install Tailscale
        shell: pwsh
        run: .github/workflows/scripts/win-install-tailscale.ps1

      - name: Establish Tailscale Connection
        shell: pwsh
        env:
          TAILSCALE_AUTH_KEY: ${{ secrets.TAILSCALE_AUTH_KEY }}
        run: .github/workflows/scripts/win-establish-ts.ps1

      - name: Verify RDP Accessibility
        shell: pwsh
        run: .github/workflows/scripts/win-verify-rdp.ps1

      - name: Maintain Connection
        shell: pwsh
        run: |
          Write-Host "`n=== RDP ACCESS ==="
          Write-Host "Address: $env:TAILSCALE_IP"
          Write-Host "Username: vum"
          Write-Host "Password: $(echo $env:RDP_CREDS)"
          Write-Host "==================`n"

          
          $DomainOrComputerName = $env:COMPUTERNAME
          $AccessRule = New-Object -TypeName System.Security.AccessControl.FileSystemAccessRule("$DomainOrComputerName\vum", "FullControl", "ContainerInherit,ObjectInherit", "None", "Allow")
          
          $FolderAcl = Get-Acl -Path "c:\"
          $FolderAcl.SetAccessRule($AccessRule)
          Set-Acl -Path "c:\" -AclObject $FolderAcl

          $FolderAcl = Get-Acl -Path "d:\"
          $FolderAcl.SetAccessRule($AccessRule)
          Set-Acl -Path "d:\" -AclObject $FolderAcl
          
          
          New-Item -Path "c:\" -Name "state.txt" -ItemType "file" -Value "true"
          
          $ACL = Get-ACL -Path "c:\state.txt"
          $AccessRule = New-Object System.Security.AccessControl.FileSystemAccessRule("vum","Full Control","Allow")
          $ACL.SetAccessRule($AccessRule)
          $ACL | Set-Acl -Path "c:\state.txt"
          
          $global:file = Get-Content "c:\state.txt"
          while ($global:file -eq "true") {
            Write-Host "[$(Get-Date)] RDP Active - Use Ctrl+C in workflow to terminate"
            Start-Sleep -Seconds 30
            $global:file = Get-Content "c:\state.txt"
          }
